package interpretador_java;

public enum TipoToken {
	IDENTIFICADOR,
	CONSTANTE_INTEIRA,
	CONSTANTE_FLOAT,
	CONSTANTE_DOUBLE,
	CONSTANTE_BOOLEANA,
	ABRE_PARENTESES,
	FECHA_PARENTESES,
	OPERADOR_ARITMETICO,
	OPERADOR_RELACIONAL,
	OPERADOR_LOGICO,
	INCREMENTADOR_DECREMENTADOR,
	OPERADOR_ATRIBUICAO,
	FIM_COMANDO,
	SEPARADOR_ARGUMENTO,
	TIPO_DADO,
	PALAVRA_RESERVADA,
	INICIO_ESCOPO,
	FIM_ESCOPO,
	
}
